name: Release

on:
  pull_request:
    types: closed

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: auto release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: "master"
          release_strategy: "release"
          tag_format: "v%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


