name: Release

on:
  pull_request:
    types: closed

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
          id: go

      - name: checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: test code
        run: go test

  release:
    runs-on: ubuntu-latest
    name: release
    needs: [test]
    steps:
      - name: auto release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: "master"
          release_strategy: "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


